"""Stable core facade for Agora framework contracts.

Advanced domain-specific contracts live under ``agora.core.<area>``.
Underscore-prefixed support modules remain internal implementation detail.
"""

from agora.core.acceptance import (
    AcceptanceFinding,
    AcceptanceGate,
    AcceptanceReport,
    AcceptanceReportProvider,
    has_acceptance_report,
)
from agora.core.checkpoint import (
    Checkpoint,
    CheckpointableSource,
    CheckpointIdentityProvider,
    CheckpointStore,
    CheckpointValue,
    InMemoryCheckpointStore,
    SourceIdentity,
    SourceIdentityMismatchError,
    SourceIdentityMismatchPolicy,
    SQLiteCheckpointStore,
    checkpoint_source_identity,
)
from agora.core.container import AgoraContainer
from agora.core.context import PipelineContext
from agora.core.data_plane import DataPlane, SinkDataPlaneSpec, SourceDataPlaneSpec
from agora.core.delivery import (
    DeliveryCapability,
    DeliveryGuarantee,
    DeliveryPolicy,
    DeliveryPolicyMismatch,
    DeliveryPolicyMismatchError,
    IdempotencyMode,
    SinkDeliveryCapability,
    SinkDeliveryCapabilityProvider,
    build_delivery_capability,
    delivery_policy_mismatches,
    enforce_delivery_policy,
    sink_delivery_capability,
)
from agora.core.discovery import discover_plugins
from agora.core.dlq import DLQRecord, DLQSink
from agora.core.dlq_policy import DLQPayloadPolicy
from agora.core.errors import (
    AgoraError,
    ConfigError,
    PipelineError,
    PluginError,
    PluginNotFoundError,
    PluginValidationError,
    RegistryError,
)
from agora.core.explain import MiddlewareStageExplain, PipelineExplain, SinkWriteExplain
from agora.core.failures import (
    AlertSeverity,
    FailureClassification,
    FailureDecision,
    PoisonRecordClassification,
    PoisonRecordInfo,
    PoisonRecordPolicy,
    classify_failure,
)
from agora.core.health import ComponentHealthSnapshot, HealthCheckable
from agora.core.metrics import (
    MetricsSnapshotProvider,
    PipelineMetrics,
    PipelineRunSummary,
    PrometheusMetricsProvider,
    has_metrics_snapshot,
    has_prometheus_metrics,
)
from agora.core.middleware import (
    FilterMiddleware,
    MapMiddleware,
    Middleware,
    RetryMiddleware,
    RouteMiddleware,
)
from agora.core.pipeline import BoundPipeline, Pipeline
from agora.core.plugin import Configurable, Lifecycle, Plugin
from agora.core.recovery import (
    SourceRecoveryContractProvider,
    SourceRecoveryContractSnapshot,
    SourceRecoveryMode,
)
from agora.core.registry import (
    AGORA_CORE_API_COMPATIBILITY,
    AGORA_CORE_API_VERSION,
    AGORA_PLUGIN_MANIFEST_VERSION,
    Registry,
)
from agora.core.retry import RetryPolicy, retry_async
from agora.core.sink import BaseSink, SinkFanOut, SinkRouter, sink_data_plane_spec
from agora.core.source import BaseSource, IterableSource, source_data_plane_spec
from agora.core.types import (
    CheckpointFailurePolicy,
    DedupStoreFailurePolicy,
    DLQFailurePolicy,
    OnError,
)
from agora.core.writer import Writer, WriteResult

_PIPELINE_EXPORTS = (
    "AgoraContainer",
    "BaseSink",
    "BaseSource",
    "BoundPipeline",
    "DataPlane",
    "FilterMiddleware",
    "IterableSource",
    "MapMiddleware",
    "Middleware",
    "Pipeline",
    "RetryMiddleware",
    "RetryPolicy",
    "RouteMiddleware",
    "SinkDataPlaneSpec",
    "SinkFanOut",
    "SinkRouter",
    "SourceDataPlaneSpec",
    "WriteResult",
    "Writer",
    "discover_plugins",
    "retry_async",
    "sink_data_plane_spec",
    "source_data_plane_spec",
)

_RECOVERY_EXPORTS = (
    "Checkpoint",
    "CheckpointIdentityProvider",
    "CheckpointFailurePolicy",
    "CheckpointStore",
    "CheckpointValue",
    "CheckpointableSource",
    "DLQFailurePolicy",
    "DLQPayloadPolicy",
    "DLQRecord",
    "DLQSink",
    "DedupStoreFailurePolicy",
    "InMemoryCheckpointStore",
    "OnError",
    "AlertSeverity",
    "FailureDecision",
    "FailureClassification",
    "PoisonRecordClassification",
    "PoisonRecordInfo",
    "PoisonRecordPolicy",
    "classify_failure",
    "SQLiteCheckpointStore",
    "SourceIdentity",
    "SourceIdentityMismatchError",
    "SourceIdentityMismatchPolicy",
    "checkpoint_source_identity",
    "SourceRecoveryContractProvider",
    "SourceRecoveryContractSnapshot",
    "SourceRecoveryMode",
    "DeliveryCapability",
    "DeliveryGuarantee",
    "DeliveryPolicy",
    "DeliveryPolicyMismatch",
    "DeliveryPolicyMismatchError",
    "IdempotencyMode",
    "SinkDeliveryCapability",
    "SinkDeliveryCapabilityProvider",
    "build_delivery_capability",
    "delivery_policy_mismatches",
    "enforce_delivery_policy",
    "sink_delivery_capability",
)

_PLUGIN_EXPORTS = (
    "AGORA_CORE_API_COMPATIBILITY",
    "AGORA_CORE_API_VERSION",
    "AGORA_PLUGIN_MANIFEST_VERSION",
    "Configurable",
    "Lifecycle",
    "Plugin",
    "Registry",
)

_OBSERVABILITY_EXPORTS = (
    "AcceptanceFinding",
    "AcceptanceGate",
    "AcceptanceReport",
    "AcceptanceReportProvider",
    "ComponentHealthSnapshot",
    "HealthCheckable",
    "MetricsSnapshotProvider",
    "PrometheusMetricsProvider",
    "MiddlewareStageExplain",
    "PipelineContext",
    "PipelineExplain",
    "PipelineMetrics",
    "PipelineRunSummary",
    "SinkWriteExplain",
    "has_acceptance_report",
    "has_metrics_snapshot",
    "has_prometheus_metrics",
)

_ERROR_EXPORTS = (
    "AgoraError",
    "ConfigError",
    "PipelineError",
    "PluginError",
    "PluginNotFoundError",
    "PluginValidationError",
    "RegistryError",
)

__all__ = [  # noqa: RUF022
    "AgoraContainer",
    "BaseSink",
    "BaseSource",
    "BoundPipeline",
    "DataPlane",
    "FilterMiddleware",
    "IterableSource",
    "MapMiddleware",
    "Middleware",
    "Pipeline",
    "RetryMiddleware",
    "RetryPolicy",
    "RouteMiddleware",
    "SinkDataPlaneSpec",
    "SinkFanOut",
    "SinkRouter",
    "SourceDataPlaneSpec",
    "WriteResult",
    "Writer",
    "discover_plugins",
    "retry_async",
    "sink_data_plane_spec",
    "source_data_plane_spec",
    "Checkpoint",
    "CheckpointIdentityProvider",
    "CheckpointFailurePolicy",
    "CheckpointStore",
    "CheckpointValue",
    "CheckpointableSource",
    "DLQFailurePolicy",
    "DLQPayloadPolicy",
    "DLQRecord",
    "DLQSink",
    "DedupStoreFailurePolicy",
    "InMemoryCheckpointStore",
    "OnError",
    "AlertSeverity",
    "FailureDecision",
    "FailureClassification",
    "PoisonRecordClassification",
    "PoisonRecordInfo",
    "PoisonRecordPolicy",
    "classify_failure",
    "SQLiteCheckpointStore",
    "SourceIdentity",
    "SourceIdentityMismatchError",
    "SourceIdentityMismatchPolicy",
    "checkpoint_source_identity",
    "SourceRecoveryContractProvider",
    "SourceRecoveryContractSnapshot",
    "SourceRecoveryMode",
    "DeliveryCapability",
    "DeliveryGuarantee",
    "DeliveryPolicy",
    "DeliveryPolicyMismatch",
    "DeliveryPolicyMismatchError",
    "IdempotencyMode",
    "SinkDeliveryCapability",
    "SinkDeliveryCapabilityProvider",
    "build_delivery_capability",
    "delivery_policy_mismatches",
    "enforce_delivery_policy",
    "sink_delivery_capability",
    "AGORA_CORE_API_COMPATIBILITY",
    "AGORA_CORE_API_VERSION",
    "AGORA_PLUGIN_MANIFEST_VERSION",
    "AcceptanceFinding",
    "AcceptanceGate",
    "AcceptanceReport",
    "AcceptanceReportProvider",
    "ComponentHealthSnapshot",
    "Configurable",
    "HealthCheckable",
    "MetricsSnapshotProvider",
    "PrometheusMetricsProvider",
    "Lifecycle",
    "Plugin",
    "Registry",
    "MiddlewareStageExplain",
    "PipelineContext",
    "PipelineExplain",
    "PipelineMetrics",
    "PipelineRunSummary",
    "SinkWriteExplain",
    "has_acceptance_report",
    "has_metrics_snapshot",
    "has_prometheus_metrics",
    "AgoraError",
    "ConfigError",
    "PipelineError",
    "PluginError",
    "PluginNotFoundError",
    "PluginValidationError",
    "RegistryError",
]
